### PR TITLE
Add support for specifying archives of bundles on command line for am…

### PR DESCRIPTION
**Pull request by jsjodin**
…dgcn.

### CODE REVIEW

**Comment by ronlieb** [comment]
LGTM,
one question, is this patch covered by an existing test? or do you need to add one to smoke?

**Comment by jsjodin** [comment]
We probably should add a test for it, but it only works on amdgcn right now. I'm working on the nvlink wrapper. I could wait with this commit until I'm done with that and add a test as well.

**Comment by ronlieb** [comment]
its fine by me , if you add the test later, forward progress and all that ...

**Comment by jsjodin** [comment]
Okay, I will merge and keep working.

**Pull request merged**
